### ISSUE TITLE
what does -infinity mean?

### ISSUE THREAD

**Issue by cristianmtr** [julian-urbano/MelodyShape#8]
Hey

I am getting some results that are -infinity in similarity score. What does this mean? I am using `shapeh2015` algorithm

**Comment by julian-urbano** [comment]
Do you have a minimum working example to reproduce?

**Comment by cristianmtr** [comment]
I just realized that it's because the sample I am using as a query does not have enough notes. Is this correct? Does the algorithm assume a minimum? I am using it to evaluate plagiarism/originality on a musical generation deep learning model

Check this zip for a query (`temp...mid`) and a file to check agains (the `c` folder). And the command that I am using (in `run.bat` file)

[mwe.zip](https://github.com/julian-urbano/MelodyShape/files/3125045/mwe.zip)

**Comment by julian-urbano** [comment]
I'm afraid so. The `ShapeH` variants work with 3-grams: https://github.com/julian-urbano/MelodyShape/blob/master/src/jurbano/melodyshape/MelodyShape.java#L126
This means that a minimum of 3 notes are needed.
